import { deckGenerator, Deck } from '../Entities/Deck';
import {
  multiOrgan,
  heart,
  liver,
  brain,
  bone,
  multiVirus,
  redVirus,
  greenVirus,
  blueVirus,
  yellowVirus,
  kit,
  vaccine,
  syrup,
  pill,
  plaster,
  // infection,
  // organThief,
  // transplant,
  // latexGlove,
  // medicalError,
} from './Cards';

export const virusDeck: Deck = deckGenerator([
  { card: multiOrgan, quantity: 1 },
  { card: heart, quantity: 5 },
  { card: liver, quantity: 5 },
  { card: brain, quantity: 5 },
  { card: bone, quantity: 5 },
  { card: multiVirus, quantity: 1 },
  { card: redVirus, quantity: 4 },
  { card: greenVirus, quantity: 4 },
  { card: blueVirus, quantity: 4 },
  { card: yellowVirus, quantity: 4 },
  { card: kit, quantity: 4 },
  { card: vaccine, quantity: 4 },
  { card: syrup, quantity: 4 },
  { card: pill, quantity: 4 },
  { card: plaster, quantity: 4 },
  // { card: infection, quantity: 2 },
  // { card: organThief, quantity: 3 },
  // { card: transplant, quantity: 3 },
  // { card: latexGlove, quantity: 1 },
  // { card: medicalError, quantity: 1 },
]);
